Added metrics for the root Marathon
dcos/grafana-dashboards pull request #33
Opened 2019-03-25 15:05 UTC by meln1k

JIRA issues: DCOS-50466

2019-03-25 19:14 UTC, gracedo requested changes
Can you make sure that you're exporting the dashboard json from grafana? ([see this comment here from another PR](https://github.com/dcos/grafana-dashboards/pull/25#discussion_r267968433))

2019-04-01 11:05 UTC, meln1k commented
@gracedo data source should be good to go now!

2019-04-01 19:11 UTC, gracedo commented
The data source is set to `null` which doesn't look quite right - can you double check that you're exporting the dashboard json directly from the Grafana UI? I would expect the diff to look something similar to [this one here](https://github.com/dcos/grafana-dashboards/pull/32/files).

2019-04-04 10:08 UTC, meln1k commented
@gracedo yes, it was copied directly from the Grafana UI.

2019-04-04 17:29 UTC, gracedo requested changes
Sorry, it's not obvious, but the `Export for sharing externally` option should be checked when exporting, that should do it! I tried it on this dashboard in SOAK and the json looks correct.
![image](https://user-images.githubusercontent.com/5897740/55575635-2a041480-56c4-11e9-9cde-cfe83626d71b.png)

2019-04-04 17:29 UTC, gracedo commented on dashboards/Marathon-Root-Summary.json
> +
Can you modify this title to a `<Component>: <Description>` format?

2019-04-05 14:06 UTC, meln1k commented
@gracedo Alright, it is fixed by now :)

2019-04-05 17:18 UTC, gracedo approved these changes
Lgtm thanks!!

2019-04-05 17:18 UTC, merged