Add metronome dashboard
dcos/grafana-dashboards pull request #45
Opened 2019-04-09 15:24 UTC by alenkacz

You can see it running here https://soak113s.testing.mesosphe.re/service/monitoring/grafana/d/6ADwfLqmz/dc-os-metronome?orgId=1

Missing values will appear when soak is updated. Those are newly introduced metrics (I've tested them on a CCM cluster).

JIRA issues: DCOS-50467, DCOS-48749

2019-04-09 22:09 UTC, gracedo requested changes
Thanks for submitting! Can you checkmark the `Export for sharing externally` option when exporting from the UI and use that json output?

![image](https://user-images.githubusercontent.com/5897740/55837072-2b26ae80-5ad5-11e9-873f-1e594bce091e.png)

2019-04-09 22:09 UTC, gracedo commented on dashboards/Metronome.json
> +  "title": "DC/OS Metronome",
Can you format the title like `<Component>: <Description>`?

2019-04-10 08:01 UTC, alenkacz commented
@gracedo Thank you. Done!

2019-04-10 16:51 UTC, gracedo commented on dashboards/Metronome.json
> +  "title": "DC/OS Metronome: Overview",
Sorry, just one tiny nit, to stay consistent with the rest of the dashboards, can we omit the DC/OS prefix from the title? (our fault for not having a clearer set of guidelines!)

2019-04-11 18:04 UTC, gracedo approved these changes
:shipit:

2019-04-11 18:04 UTC, merged