Add dashboard for ErlangVM
dcos/grafana-dashboards pull request #69
Opened 2019-07-02 14:04 UTC by Fabs

Adding Graphs for the Erlang VM. You can this dashboard on soak113s.

![image](https://user-images.githubusercontent.com/10524/60519057-0a8c8000-9ce3-11e9-9eb5-56c9f906a113.png)

2019-07-02 15:46 UTC, urbanserj commented
@Fabs could you please remove `Erlang` from `Networking: Erlang VM`? it will just cause more questions, nobody cares while they don't know what stack we are using.

2019-07-03 13:13 UTC, Fabs commented
@urbanserj done.

2019-07-03 16:11 UTC, philipnrmn requested changes
Nice work Fabs! Especially loving the helpful descriptions.

I have some minor grammar and spelling fixes, and also there's a missing quote which invalidates the JSON at the bottom.

2019-07-03 16:11 UTC, philipnrmn commented on dashboards/Networking/Networking-VM.json
> +      "content": "This are the set of panels about VM CPU consumption.\n \n**VM GC**: Shows the number of GCs performmed and how many bytes they reclaimed. With multiple hosts show the `max` bytes re
```suggestion
      "content": "This set of panels shows VM CPU consumption.\n \n**VM GC**: Shows the number of GCs performed and how many bytes they reclaimed. With multiple hosts, shows the `max` bytes reclaimed and the `max` number of GC among the hosts.\n\n**Queues Length**: Shows the queue length of the selected host.\n\n**Load**: shows the number of Reductions and Context Switches performed by the [VM scheduler](https://hamidreza-s.github.io/erlang/scheduling/real-time/preemptive/migration/2016/02/09/erlang-scheduler-details.html).\n\n**Processes**: shows the total number of processes and ports ready to run at any given run-queue, the total number of process current running at the node and the limit in number of processes when set.",
```

2019-07-03 16:11 UTC, philipnrmn commented on dashboards/Networking/Networking-VM.json
> +  title": "Networking: VM",
```suggestion
  "title": "Networking: VM",
```

2019-07-03 16:11 UTC, philipnrmn commented on dashboards/Networking/Networking-VM.json
> +      "content": "This are the set of panels about Uptime.\n \n**Uptime**: This host uptime in hours.\n\n**Uptime: Longest Running VMs**: Longest living VMs based on top 5 uptime.\n\n**Uptime: Most R
```suggestion
      "content": "This set of panels shows uptime.\n \n**Uptime**: This host's uptime in hours.\n\n**Uptime: Longest Running VMs**: Longest living VMs based on top 5 uptime.\n\n**Uptime: Most Recent Restarts**: Most recent restarts based on bottom 5 uptime.",
```

2019-07-03 16:11 UTC, philipnrmn commented on dashboards/Networking/Networking-VM.json
> +      "content": "This are the set of panels about VM Memory consumption.\n\n**VM Memory**: This graph shows the total memory used by the system + `processes`. The `system` memory is further broken d
```suggestion
      "content": "This set of panels shows VM Memory consumption.\n\n**VM Memory**: This graph shows the total memory used by the system + `processes`. The `system` memory is further broken down according to the type of usage `atoms`, `binary`, `code` and `ets` tables.",
```

2019-07-03 16:11 UTC, philipnrmn commented on dashboards/Networking/Networking-VM.json
> +      "content": "This are the set of panels about VM I/O.\n\n**VM IO**: rate of bytes transfered in and out the VM of the selected Host.\n\n**Ports**: the VM total open [Ports](http://erlang.org/doc
```suggestion
      "content": "This set of panels shows VM I/O.\n\n**VM IO**: rate of bytes transferred in and out the VM of the selected Host.\n\n**Ports**: the VM total open [ports](http://erlang.org/doc/reference_manual/ports.html) as well as the max ports available (dotted red line) if defined.",
```

2019-07-03 18:03 UTC, Fabs commented on dashboards/Networking/Networking-VM.json
> +  title": "Networking: VM",
Oh a lot, thanks for that one :)

2019-07-05 13:51 UTC, Fabs commented
@philipnrmn, thanks a lot for the review, could you please look at it again?

2019-07-10 17:11 UTC, philipnrmn approved these changes

2019-07-10 17:11 UTC, merged