Add Edge-LB dashboards
dcos/grafana-dashboards pull request #73
Opened 2019-07-17 15:21 UTC by vespian

## High-level description (required)

This PR adds the following dashboards for Edge-LB:
* Go runtime overview
* Go runtime memory usage details
* Haproxy metrics

The HAProxy has a separate LICENSE file as we are extending an LGPL-licensed dashboard created by @rfrail3 [1]. CC: @mattj-io There is also licensing information along with the mention of the author of the base dashboard at the bottom of the `Edge-LB_ Pool server - HAProxy.json` itself.

[1] https://github.com/rfrail3/grafana-dashboards/blob/master/prometheus/haproxy-full.json

2019-07-17 15:24 UTC, vespian commented
@mattj-io Do we need to modify the root folder's license file somehow (i.e. it's Apache 2.0) so that it mentions that individual dashboards can have different license, or is having the separate folder plus a note in the dashboard itself enough?

2019-07-17 15:28 UTC, vespian commented
@philipnrmn @gracedo @branden Could you please have a look? The licensing was already discussed with Matt and Nathan.

2019-07-23 17:55 UTC, gracedo requested changes
Can you remove the spaces from these filenames? Otherwise lgtm

2019-07-23 17:55 UTC, gracedo commented on dashboards/Edge-LB/Edge-LB_ Pool server - HAProxy/Edge-LB_ Pool server - HAProxy.json
> +
nit: can we capitalize `Server`?

2019-07-23 19:42 UTC, vespian commented
@gracedo Done, ready for next pass!

Could you also have a look at the backport, please? 

https://github.com/dcos/grafana-dashboards/pull/74

2019-07-23 20:38 UTC, gracedo approved these changes

2019-07-23 20:39 UTC, merged