add csilvm pv metrics, persist other unsaved changes
dcos/grafana-dashboards pull request #75
Opened 2019-07-29 14:37 UTC by gpaul

2019-07-29 15:03 UTC, bbannier approved these changes
A little hard to see exactly what happened here, but makes sense to me. Yee-haw!

2019-07-30 22:45 UTC, philipnrmn commented on dashboards/Storage-Summary.json
> +      "datasource": "prometheus",
```suggestion
      "datasource": "${DS_PROMETHEUS}",
```

2019-07-30 22:45 UTC, philipnrmn commented on dashboards/Storage-Summary.json
> +      "datasource": "prometheus",
```suggestion
      "datasource": "${DS_PROMETHEUS}",
```

2019-07-30 22:46 UTC, philipnrmn commented on dashboards/Storage-Summary.json
> +      "datasource": "prometheus",
```suggestion
      "datasource": "${DS_PROMETHEUS}",
```

2019-07-30 22:46 UTC, philipnrmn commented on dashboards/Storage-Summary.json
> +      "datasource": "prometheus",
```suggestion
      "datasource": "${DS_PROMETHEUS}",
```

2019-07-30 22:49 UTC, philipnrmn commented
Exporting the dashboard via the 'share->export' dialog and ticking the 'export for sharing externally' box will fix the datasource issue:

![image](https://user-images.githubusercontent.com/2989362/62170793-8f1dee80-b2e1-11e9-8a2b-baada5fb5c41.png)

2019-07-30 22:49 UTC, philipnrmn requested changes
(otherwise, lgtm)

2019-07-31 08:47 UTC, gpaul commented
@philipnrmn thanks! Good spot! Also, that export trick is exactly what i was looking for. Unfortunately it didn't _quite_ work as we appear to have removed a bunch of alerts which I'm not sure we really wanted to remove. Anyway, I've fixed the datasource fields, thanks.

2019-07-31 18:47 UTC, philipnrmn approved these changes

2019-07-31 18:48 UTC, merged