WIP: add metrics for Calico in DC/OS
dcos/grafana-dashboards pull request #99
Opened 2019-12-31 09:52 UTC by mainred

This PR introduced a dashboard for Calico, mainly Calico Felix, metric.

The metrics show up in this dashboard are collected by https://github.com/dcos/dcos/pull/6709, so we need first merge https://github.com/dcos/dcos/pull/6709 before this dashboard works as expected.

## Corresponding DC/OS tickets

- [DCOS-60156](https://jira.mesosphere.com/browse/DCOS-60156) add metrics for calico in DC/OS

2019-12-31 09:53 UTC, mainred commented
![image](https://user-images.githubusercontent.com/1465768/71617507-5f5b7580-2bf6-11ea-9277-4d87a9dfd66d.png)
![image](https://user-images.githubusercontent.com/1465768/71617527-700beb80-2bf6-11ea-81d9-a8c82ba16fda.png)
![image](https://user-images.githubusercontent.com/1465768/71617545-7bf7ad80-2bf6-11ea-855a-28f734e83bc6.png)

2020-01-07 10:40 UTC, DominikDary commented
👍

2020-01-07 10:40 UTC, DominikDary approved these changes

2020-01-07 10:41 UTC, DominikDary commented
@philipnrmn can you please help getting this merged?

2020-01-07 22:59 UTC, philipnrmn commented
Please templatize the prometheus datasource, as seen in https://github.com/dcos/grafana-dashboards/blob/master/dashboards/Networking/Networking-DNS.json#L3-L10

2020-01-07 22:59 UTC, philipnrmn requested changes
Please modify the datasources to use a template variable, as in https://github.com/dcos/grafana-dashboards/blob/master/dashboards/Networking/Networking-DNS.json#L3-L10

2020-01-08 06:00 UTC, mainred commented
@philipnrmn , could you please take another look?

2020-01-09 08:20 UTC, DominikDary approved these changes

2020-01-09 08:20 UTC, DominikDary commented
Thanks for the change @mainred

2020-01-09 08:20 UTC, merged